name: file_licenser
description: A command-line application to add licenses to all dart files in a directory.
version: 3.0.0
repository: https://github.com/mosuem/file_licenser

environment:
  sdk: '>=2.18.0 <4.0.0'
dependencies:
  yaml: ^3.1.3
